#!/usr/local/bin/node


var socket = require('socket.io-client')('http://127.0.0.1:23232');

function sendit() {
	socket.on('ack',function(){
		process.exit();
	});
	
	socket.emit('ctrl',process.argv[2], function(data){
		console.log('ack');
		process.exit();
	});
}

socket.on('connect', function(){

	if(process.argv[2] === "online")
	{
		setTimeout(function(){socket.emit('ctrl','load')},2000);
		setTimeout(sendit,10000);
	}
	else
	{
		sendit();
	}
});
	
setTimeout(process.exit,13000);

