#!/bin/sh

while true
do
	ffmpeg -y -v quiet -i `find /dev/shm/mytv2/live_src/*.ts | tail -1` -i /usr/local/nginx/html/overlay.png -filter_complex "[0:v]boxblur=8:1,scale=640:360[zork];[1:v]format=rgba,geq=r='r(X,Y)':a='0.5*alpha(X,Y)',[zork]overlay" -q:v 5 -vsync vfr -update 1 -vframes 1 /dev/shm/img2.jpg
	ffmpeg -y -v quiet -i `find /dev/shm/mytv2/live_src/*.ts | tail -1`  -vf "boxblur=8:1,scale=640:360" -q:v 5 -vsync vfr -vframes 1 -update 1 /dev/shm/img.jpg
	sleep 10
done

